### PR TITLE
Resurrect PyROOT regression tests

### PR DESCRIPTION
**Pull request by vepadulano**
Never run because of `--fixcling` command line argument.

### CODE REVIEW

**Comment by vepadulano** [comment]
@phsft-bot build

**Comment by dpiparo** [comment]
Thanks for this PR and apologies for not reviewing before. I am a bit concerned by all these errors, so near the release. I will treat this with a lot of care, with the objective of having it in master and 6.28 asap.

**Comment by dpiparo** [comment]
@phsft-bot build

**Comment by vepadulano** [comment]
@dpiparo FYI this should be good to go now :+1:

**Comment by dpiparo** [comment]
I agree. Sorry for the delay. Can merge perhaps next week, in case something unexpected happens?

**Review by dpiparo — APPROVED** [review]
lgtm, thanks.

**Comment by vepadulano** [comment]
@phsft-bot build

**Pull request merged**
