### PR TITLE
[cling] Add test for function with try-catch body

### PR DESCRIPTION
**Pull request by hahnjo**
See https://github.com/root-project/root/issues/9664 for context.

### CODE REVIEW

**Comment by vgvassilev** [comment]
Ok, that should do. Normally, for cling-related changes we extend the test suite in cling. That helps the standalone case.

**Comment by hahnjo** [comment]
> Ok, that should do. Normally, for cling-related changes we extend the test suite in cling. That helps the standalone case.

I somehow had in my head that it's not enabled in standalone Cling, but there indeed seems to be `interpreter/cling/test/Extensions/ImplicitAutoKeyword/`. However, all tests in there are `XFAIL: *` and I think Cling tests are generally not run for ROOT PRs, are they?

**Comment by hahnjo** [comment]
@bellenot this is the test I mentioned, somehow I don't get the output from the `catch` block on Windows. Is there a problem with throwing integers on Windows?

**Comment by bellenot** [comment]
@hahnjo well, not sure how well the exception handling works on Windows. It's still something I have to figure out. I would suggest to disable this test on Windows for the time being, until I manage to fix EH on Win32 and Win64...

**Comment by hahnjo** [comment]
The failures in `roottest/cling/exception` are because I don't have #803 in the branch.

**Comment by hahnjo** [comment]
Now correctly disabled on Windows:
```
21:19:16            Start  371: roottest-cling-function-trybody_WILL_FAIL
21:19:18   397/1244 Test  #371: roottest-cling-function-trybody_WILL_FAIL .................................................   Passed    2.43 sec
```

Good to merge, @Axel-Naumann @vgvassilev ?

**Review by Axel-Naumann — APPROVED** [review]
LGTM thanks!

**Comment by Axel-Naumann** [comment]
(FYI and *for the future*, cling repairs that don't involve ROOT at all often have their test added in `interpreter/cling/test`, so standalone cling sees these tests, too.)

**Comment by hahnjo** [comment]
> (FYI and _for the future_, cling repairs that don't involve ROOT at all often have their test added in `interpreter/cling/test`, so standalone cling sees these tests, too.)

see

> > Ok, that should do. Normally, for cling-related changes we extend the test suite in cling. That helps the standalone case.
> 
> I somehow had in my head that it's not enabled in standalone Cling, but there indeed seems to be `interpreter/cling/test/Extensions/ImplicitAutoKeyword/`. However, all tests in there are `XFAIL: *` and I think Cling tests are generally not run for ROOT PRs, are they?

**Comment by Axel-Naumann** [comment]
Of course you're right, @hahnjo , thanks for correcting me!

**Pull request merged**
