### PR TITLE
Use different file names to avoid the concurrent access issue in parallel

### PR DESCRIPTION
**Pull request by PointKernel**

### CODE REVIEW

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by pcanal** [comment]
@PointKernel Can you also update your root repository fork master branch to match the current main ROOT repository master to avoid the merge failure?

**Comment by PointKernel** [comment]
done, should be OK right now.

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Pull request merged**
