### PR TITLE
Test for issue #7754

### PR DESCRIPTION
**Pull request by pcanal**

### CODE REVIEW

**Comment by pcanal** [comment]
@phsft-bot build

**Comment by pcanal** [comment]
@phsft-bot build

**Comment by pcanal** [comment]
@bellenot Fun windows failure :) [`compiler is out of heap space ...`]

**Comment by pcanal** [comment]
The failures are unrelated.

**Comment by bellenot** [comment]
> @bellenot Fun windows failure :) [`compiler is out of heap space ...`]

Yes, I know... 🙁

**Pull request merged**
