### PR TITLE
[TSEQ] Add test for TSeq::iterator class

### PR DESCRIPTION
**Pull request by bluehood**

### CODE REVIEW

**Comment by xvallspl** [comment]
Do we need reference files for tests like this? It already returns 0 if it passes. Seems redundant.

**Comment by dpiparo** [comment]
no we do not actually. If no ref file is specified, we can check the retcode, by default expected to be 0.

**Comment by bluehood** [comment]
My fault, sorry. I wouldn't open another PR just for that, maybe Danilo could you remove the reference with a ninja commit? :) Otherwise I'll open a PR

**Comment by xvallspl** [comment]
Dit it myself, PR coming

**Comment by dpiparo** [comment]
cool, looking forward!

**Comment by bluehood** [comment]
thank you!

**Pull request merged**
