### PR TITLE
Add test against ROOT-10777.

### PR DESCRIPTION
**Pull request by Axel-Naumann**
Should fail now and should get fixed by https://github.com/root-project/root/pull/5639

### CODE REVIEW

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Comment by pcanal** [comment]
Please rebase on master.

**Comment by pcanal** [comment]
https://github.com/root-project/roottest/pull/520 needs to be rebased on master to remove the filemerger error.

**Comment by Axel-Naumann** [comment]
@phsft-bot build

**Comment by Axel-Naumann** [comment]
root-project/root#5639 was fixed in the meantime, fixing projectroot.roottest.root.meta.autoloading.headerParsingOnDemand.roottest_root_meta_autoloading_headerParsingOnDemand_runFullheaderParsingOnDemand on later builds.

**Pull request merged**
