### PR TITLE
Add test for random access compression

### PR DESCRIPTION
**Pull request by zzxuanyuan**
This is a unit test for Random Access Compression. It created two files. One is written with RAC and the other without RAC.

### CODE REVIEW

**Comment by pcanal** [comment]
Did you test reading the file produce with the new code and the new feature disabled with an older version of ROOT?   Did you test reading the file produced with the new feature with an older version of ROOT?

**Comment by xvallspl** [comment]
@pcanal @zzxuanyuan Is this still relevant?

**Comment by etejedor** [comment]
@pcanal @zzxuanyuan are we ready to merge this?

**Comment by zzxuanyuan** [comment]
@etejedor

**Pull request closed without merging**
