### PR TITLE
[Python][pytest] Remove inbuilt pytest

### PR DESCRIPTION
**Pull request by stwunsch**
This removes the inbuilt pytest and takes it from the system. Works fine on my machine but most likely the CI is missing the pytest package.

@oshadura How do we typically search for python modules? I've just put in something that works. Also, I'm not sure whether everything still works with an external root.

Fixes https://github.com/root-project/root/issues/6597

### CODE REVIEW

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by Axel-Naumann** [comment]
I like that CMake fails in case pytest is missing and roottest is on!

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by stwunsch** [comment]
> Build failed on ROOT-performance-centos8-multicore/default.
> Running on null:/data/sftnight/workspace/roottest-pullrequests-build
> [See console output](https://lcgapp-services.cern.ch/root-jenkins/job/roottest-pullrequests-build/7374/console).
> 
> ### Errors:
> * [2020-10-09T16:17:52.995Z] CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
> * [2020-10-09T16:17:53.510Z] CMake Error at /data/sftnight/workspace/roottest-pullrequests-build/rootspi/jenkins/root-build.cmake:1051 (message):

@oshadura Could you install pytest for python2 and python3 on that machine? Or do I have sudo rights there?

**Comment by stwunsch** [comment]
@oshadura @etejedor This PR seems to work well! The only issue I see is that we have to install pytest on all nodes and decide on how to behave with roottest in case pytest is not found. The current behaviour is throwing a configuration error.

**Comment by oshadura** [comment]
@phsft-bot build just on ROOT-performance-centos8-multicore/default

**Comment by oshadura** [comment]
@stwunsch pytest is installed on ROOT-performance-centos8-multicore/default

**Comment by oshadura** [comment]
@phsft-bot build!

**Review by oshadura — APPROVED** [review]
definitely LGTM!!!

**Comment by oshadura** [comment]
@Axel-Naumann I would like to merge it but I am not sure if on all machines are installed pytest?

**Comment by oshadura** [comment]
(otherwise when @stwunsch  is back we can install altogether, e.g. for nighlies/incrementals/rootbench and etc.)

**Comment by stwunsch** [comment]
Let me run the CI a few times, that way we should cycle through all the nodes and minimize the fallout once we merge.

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by stwunsch** [comment]
@oshadura @Axel-Naumann  Does this change have implication wrt to LCG and friends? How should we propagate this change to the interested parties? Release notes?

**Comment by stwunsch** [comment]
@phsft-bot build

**Comment by stwunsch** [comment]
Rebased on master to fix the CI issues from the last run

**Comment by stwunsch** [comment]
@phsft-bot build

**Review by etejedor — APPROVED** [review]

**Pull request merged**
