### PR TITLE
Increasing tolerance for aarch64 fast-math builds (different precision)

### PR DESCRIPTION
**Pull request by oshadura**

### CODE REVIEW

**Comment by oshadura** [comment]
@pcanal can you take a look please?

**Comment by oshadura** [comment]
@pcanal thank you for such elegant idea, i checked on aarch64 with fast math, test is green!

**Comment by oshadura** [comment]
@amadio PR with new tolerances!

**Comment by amadio** [comment]
@oshadura Let me merge the fix for the test I broke last night, then we can proceed here. (If the references are not from yesterday after my merges or from today, they should be ok, though).

**Pull request merged**
