### PR TITLE
Enable ROOT_SOURCE_DIR for standalone roottest.git

### PR DESCRIPTION
**Pull request by oshadura**
In addition it fixes some broken tests: https://gist.github.com/oshadura/f3de048f8a046ae83143e5f35990ccf6

### CODE REVIEW

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by Axel-Naumann** [comment]
@oshadura can and should this be merged into master before the v6.18 branch?

**Comment by oshadura** [comment]
It enables standalone testing in case if ROOT is used from build directory and roottest.git is standalone (there are failing ~12 tests but I can fix them in separate PR). Related to https://github.com/root-project/roottest/pull/305

**Comment by oshadura** [comment]
@Axel-Naumann can you merge it when it will be green?

**Comment by linev** [comment]
Yes, it works for me now. 
But this is wrong way - re-detect lz4 once again with potentially wrong assumption.

**Comment by Axel-Naumann** [comment]
> Yes, it works for me now.

I suggest we merge this now (to enable testing a install of root), and we fix remaining issues in subsequent PRs. Objections? Else I'll merge today.

**Comment by linev** [comment]
@Axel-Naumann 
You can merge - it is better than before.
But it keep places for confusion in the future - roottest may produce wrong failure messages although everything is fine.

**Comment by Axel-Naumann** [comment]
@amadio agreed, too - merging!

**Pull request merged**
