### PR TITLE
Improvements and fixes for the tExecutor test

### PR DESCRIPTION
**Pull request by xvallspl**
still feels hackish and should be moved to gtest together with threadExecutor and processExecutor

### CODE REVIEW

**Comment by xvallspl** [comment]
@bellenot any idea why the rebase would fail on Windows?

**Comment by xvallspl** [comment]
Investigating these consistent timeouts...

**Comment by bellenot** [comment]
> @bellenot any idea why the rebase would fail on Windows?

No idea...

**Comment by xvallspl** [comment]
> > @bellenot any idea why the rebase would fail on Windows?
> 
> No idea...

I'll build again. @phsft-bot build

**Comment by xvallspl** [comment]
oops @phsft-bot build just on windows10/cxx14

**Comment by xvallspl** [comment]
@phsft-bot build just on windows10/cxx14

**Comment by xvallspl** [comment]
Just updated the master branch in the windows node, which was 214 commits behind master.

@phsft-bot build just on windows10/cxx14

**Pull request merged**
