### PR TITLE
Refactoring and moving to CMake root-tree-fastcloning tests

### PR DESCRIPTION
**Pull request by oshadura**

### CODE REVIEW

**Comment by oshadura** [comment]
@pcanal, locally this PR is green, but it should land after only after https://github.com/root-project/roottest/pull/289

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by oshadura** [comment]
windows failure looks unconnected to the changes: `11:16:27 Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
11:16:27    at Microsoft.Build.Logging.ConfigurableForwardingLogger.ErrorHandler(Object sender, BuildErrorEventArgs e)
11:16:27    at Microsoft.Build.Framework.BuildErrorEventHandler.Invoke(Object sender, BuildErrorEventArgs e)
11:16:27    at Microsoft.Build.BackEnd.Logging.EventSourceSink.RaiseErrorEvent(Object sender, BuildErrorEventArgs buildEvent)
11:16:27    at Microsoft.Build.BackEnd.Logging.EventSourceSink.Consume(BuildEventArgs buildEvent)
11:16:27    at Microsoft.Build.BackEnd.Logging.LoggingService.RouteBuildEvent(BuildEventArgs eventArg)
11:16:27    at Microsoft.Build.BackEnd.Logging.LoggingService.RouteBuildEvent(Object loggingEvent)
11:16:27    at Microsoft.Build.BackEnd.Logging.LoggingService.LoggingEventProcessor(Object loggingEvent)
11:16:27    at Microsoft.Build.BackEnd.Logging.LoggingService.<CreateLoggingEventQueue>b__98_0(Object loggingEvent)
11:16:27    at System.Threading.Tasks.Dataflow.ActionBlock`1.ProcessMessage(Action`1 action, KeyValuePair`2 messageWithId)
11:16:27    at System.Threading.Tasks.Dataflow.ActionBlock`1.<>c__DisplayClass5.<.ctor>b__0(KeyValuePair`2 messageWithId)
11:16:27    at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.ProcessMessagesLoopCore()
11:16:27    at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.<ProcessAsyncIfNecessary_Slow>b__3(Object thisTargetCore)
11:16:27    at System.Threading.Tasks.Task.InnerInvoke()
11:16:27    at System.Threading.Tasks.Task.Execute()`

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by oshadura** [comment]
@pcanal I think we are green here, I rebased on master.

**Pull request merged**
