### PR TITLE
[FreeBSD] Be explicit that gmake is required

### PR DESCRIPTION
**Pull request by mkrzewic**
this makes yet another batch of tests pass on FreeBSD

### CODE REVIEW

**Comment by pcanal** [comment]
What is the difference between `make` and `gmake` on `FreeBSD` (and/or why does it fail without the `g` :))

**Comment by mkrzewic** [comment]
> What is the difference between `make` and `gmake` on `FreeBSD` (and/or why does it fail without the `g` :))

make is the bsd make, does not speak the gnu make dialect...

**Comment by hahnjo** [comment]
@phsft-bot build just on ROOT-debian10-i386/soversion, ROOT-ubuntu2004/python3, mac11/noimt, mac12arm/cxx20

**Review by hahnjo — CHANGES_REQUESTED** [review]
`gmake` is not available on all systems. We likely need a CMake check: If `gmake` is found, use that; otherwise fall back to `make` and hope that it is GNU...

**Comment by mkrzewic** [comment]
so maybe like this?

**Comment by pcanal** [comment]
Unfortunately according to https://cmake.org/cmake/help/latest/variable/CMAKE_MAKE_PROGRAM.html:
```
The [Ninja](https://cmake.org/cmake/help/latest/generator/Ninja.html#generator:Ninja) generator sets this to ninja.
```

**Comment by mkrzewic** [comment]
@pcanal, ah indeed, I see.

**Comment by hahnjo** [comment]
@phsft-bot build

**Comment by hahnjo** [comment]
@phsft-bot build!

**Comment by mkrzewic** [comment]
I don't have access to the CI output but on ubuntu I get:

```
CMake Error at /local/mkrzewic/build/root/builtins/davix/DAVIX-prefix/src/DAVIX-stamp/DAVIX-build-RelWithDebInfo.cmake:49 (message):
Command failed: 2

'/usr/bin/gmake'

See also

/local/mkrzewic/build/root/builtins/davix/DAVIX-prefix/src/DAVIX-stamp/DAVIX-build-*.log
```

with log:

```
CMake Warning at CMakeLists.txt:51 (message):
the curl cmake build system is poorly maintained.  Be aware


Found *nroff option: -- -man
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
/usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
/usr/share/cmake-3.22/Modules/FindOpenSSL.cmake:574 (find_package_handle_standard_args)
CMakeLists.txt:365 (find_package)

gmake[5]: *** [CMakeFiles/BuildCurlBundled.dir/build.make:92: deps/curl/src/BuildCurlBundled-stamp/BuildCurlBundled-configure] Error 1
gmake[4]: *** [CMakeFiles/Makefile2:214: CMakeFiles/BuildCurlBundled.dir/all] Error 2
gmake[4]: *** Waiting for unfinished jobs....
gmake[3]: *** [Makefile:136: all] Error 2
```

seems unrelated?

**Comment by jalopezg-git** [comment]
@phsft-bot build

**Review by hahnjo — APPROVED** [review]
This seems to work now. Can you maybe restore the indentation as it was before? If not, I'll do this later today and / or land as-is.

**Comment by mkrzewic** [comment]
@hahnjo sure, done

**Pull request merged**
