### PR TITLE
 Update in references of I/O related tests after introducing zlib-cf 

### PR DESCRIPTION
**Pull request by oshadura**

### CODE REVIEW

**Comment by oshadura** [comment]
@phsft-bot build!

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by oshadura** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
@phsft-bot build with flags -DCTEST_TEST_EXCLUDE_NONE=On

**Comment by pcanal** [comment]
Due to the 'windows' 'worker' being unavailable, the test result are not showing up properly.  The only platform failing is the one where module are enabled and that is like because the corresponding roottest branch does not include the modification necessary for the last PR merge (related to module, https://github.com/root-project/root/pull/3695

**Pull request merged**
