### PR TITLE
Custom allocator fixes

### PR DESCRIPTION
**Pull request by hahnjo**
Required to pass tests with newer versions of `libstdc++`.

### CODE REVIEW

**Review by Axel-Naumann — APPROVED** [review]
LGTM thanks! (Could've been nice to mention the motivation for the change in the second commit's log, but we'll survive.)

**Comment by hahnjo** [comment]
> Could've been nice to mention the motivation for the change in the second commit's log, but we'll survive.

I can add that, at least the part that I understand...

**Review by jalopezg-git — COMMENTED** [review]
Thanks, @hahnjo :slightly_smiling_face:!  Don't forget to run `clang-format` on this patch -- there seems to be some code style inconsistency.

**Comment by hahnjo** [comment]
> Don't forget to run `clang-format` on this patch -- there seems to be some code style inconsistency.

Done. At least partially, `clang-format` wanted to add another space before `public:` which is not our code style...

**Pull request merged**
