### PR TITLE
[meta] Remove cling workaround with runtime check for modules

### PR DESCRIPTION
**Pull request by dpiparo**
Fixes https://github.com/orgs/root-project/projects/8/views/1?pane=issue&itemId=52382006

### CODE REVIEW

**Comment by dpiparo** [comment]
fixes https://github.com/root-project/root/issues/14586

**Review by pcanal — APPROVED** [review]

**Comment by pcanal** [comment]
The test are not related but should not be failing.  Do we understand what is going on there?

**Comment by dpiparo** [comment]
I am not sure, @pcanal (btw, thanks for having a look). I am investigating.

**Comment by dpiparo** [comment]
One is related to the notebook version installed on the node. The other is stdout/stderr that for some reason got to the log file in the wrong order. One is due to a signed/unsigned integer comparison (which we can fix, minimal). The most serious is [projectroot.roottest.root.dataframe.roottest_root_dataframe_test_stringfiltercolumn](https://lcgapp-services.cern.ch/root-jenkins/job/roottest-pullrequests-build/13553/testReport/projectroot.roottest.root/dataframe/roottest_root_dataframe_test_stringfiltercolumn/). 
```
Cluster #48 starts at 1770 and ends at 1799
 ******************************************************************************
 *Tree    :t1        :                                                        *
-*Entries :     1800 : Total =           29346 bytes  File  Size =      17979 *
+*Entries :     1800 : Total =           29346 bytes  File  Size =      17978 *
 *        :          : Tree compression factor =   1.59                       *
 ******************************************************************************
 Cluster Range #  Entry Start      Last Entry           Size   Number of clusters
@@ -221,7 +221,7 @@
 Cluster #68 starts at 2370 and ends at 2399
 ******************************************************************************
 *Tree    :t1        :                                                        *
-*Entries :     2400 : Total =           33566 bytes  File  Size =      20849 *
+*Entries :     2400 : Total =           33566 bytes  File  Size =      20852 *
 *        :          : Tree compression factor =   1.56                       *
 ******************************************************************************
 Cluster Range #  Entry Start      Last Entry           Size   Number of clusters
 ```
Since this IO, I am not inclined to say it's a fluctuation and would like to ask your opinion, @pcanal

**Comment by pcanal** [comment]
@phsft-bot build just on ROOT-performance-centos8-multicore/soversion

**Comment by pcanal** [comment]
> Since this IO, I am not inclined to say it's a fluctuation 

This should not have changed.  Do we see this problem on other PRs?

**Comment by pcanal** [comment]
@phsft-bot build just on ROOT-performance-centos8-multicore/soversion

**Comment by vepadulano** [comment]
@phsft-bot build

**Comment by vepadulano** [comment]
@dpiparo Can you rebase this branch on latest roottest master? Since you are only changing a test and nothing implementation-wise, I find it very hard to believe those failures are real, and at least for the Jupyter ones I know there were independent fixes provided in the past days

**Comment by dpiparo** [comment]
yes, @vepadulano you are right, I need to do that now.

**Pull request merged**
