### PR TITLE
Fix test_snapshot_copyaddresses.C on Windows

### PR DESCRIPTION
**Pull request by bellenot**
Fix issue with files not being deleted on Windows due to file handles not yet released by the process

### CODE REVIEW

**Review by eguiraud — CHANGES_REQUESTED** [review]
Hi @bellenot , thank you, I'm still surprised that `Unlink` fails without the usual message that says "cannot delete already opened file" or something like that, but :man_shrugging: 

Just two small things:
- the indentation of the code inside braces is now wrong :smile:
- please add a comment mentioning why we need these seemingly no-op braces in the code, or someone might "optimize" them away in the future

**Comment by bellenot** [comment]
@eguiraud OK, thanks. I'll correct the indentation and add a comment

**Review by eguiraud — APPROVED** [review]
Thanks a lot Bertrand!

**Comment by bellenot** [comment]
@eguiraud You're very welcome! :-)

**Comment by bellenot** [comment]
The failure is unrelated. Merging

**Pull request merged**
