### PR TITLE
Revert "[DF] Disable distributed tests on M1 ARM"

### PR DESCRIPTION
**Pull request by hahnjo**
This reverts commit 3971a5488667a8d1a5d7a52228bc56cfe735ef2f.

Closes https://github.com/root-project/root/issues/10061

### CODE REVIEW

**Comment by hahnjo** [comment]
@phsft-bot build just on mac11arm/default, mac12arm/default, mac13arm/default

**Comment by hahnjo** [comment]
Ok, mac11arm and mac12arm didn't run the tests, but mac13arm did; I'm a bit confused by the failure in https://lcgapp-services.cern.ch/root-jenkins/job/roottest-pullrequests-build/12233/testReport/projectroot.roottest.python.distrdf/dask/roottest_python_distrdf_dask_test_all/ - that looks like the test is throwing an exception somewhere which we know doesn't work in M1. @vepadulano would it make sense to only disable that one (part of the) test?

**Comment by vepadulano** [comment]
Yes that test precisely throws an exception on bad usage of `Graph` so if that doesn't work we should disable it.

**Comment by hahnjo** [comment]
> Yes that test precisely throws an exception on bad usage of `Graph` so if that doesn't work we should disable it.

Maybe stupid question: How do we do that? Can we check for Apple & AArch64 and then disable the tests involving exceptions? Do we already have an existing test that does this, from which I could copy?

**Comment by hahnjo** [comment]
@phsft-bot build just on mac11arm/default, mac12arm/default, mac13arm/default with flags -DCTEST_TEST_EXCLUDE_NONE=ON

**Comment by hahnjo** [comment]
@phsft-bot build just on mac12arm/default, mac13arm/default with flags -DCTEST_TEST_EXCLUDE_NONE=ON

**Comment by vepadulano** [comment]
> Build failed on mac13arm/default. Running on 194.12.149.74:/Users/sftnight/build/workspace/roottest-pullrequests-build [See console output](https://lcgapp-services.cern.ch/root-jenkins/job/roottest-pullrequests-build/13251/console).
> ### Failing tests:
> 
>     * [projectroot.roottest.python.distrdf.dask.roottest_python_distrdf_dask_test_all](https://lcgapp-services.cern.ch/root-jenkins/job/roottest-pullrequests-build/13251/testReport/projectroot.roottest.python.distrdf/dask/roottest_python_distrdf_dask_test_all/)

I have started to see this failure on DistRDF + Dask tests today for the first time. But it seems it's not strictly related to this PR (or MacOS in general), e.g. https://github.com/root-project/root/pull/13912#issuecomment-1773534878 or https://github.com/root-project/root/runs/17955813786 .

Investigating :+1:

**Comment by hahnjo** [comment]
I'm not sure it's the same:
```
libc++abi: terminating due to uncaught exception of type std::runtime_error: Graph was applied to a mix of scalar values and collections. This is not supported.
```
is a C++ exception which we cannot catch on Apple Silicon. I already described this in https://github.com/root-project/roottest/pull/936#issuecomment-1436999157 and I continue to think we need to disable this test.

The other two are `ZeroDivisionError: division by zero`, which I also don't see in the link above...

**Comment by hahnjo** [comment]
@phsft-bot build just on mac13arm/default with flags -DCTEST_TEST_EXCLUDE_NONE=ON

**Review by vepadulano — APPROVED** [review]
Indeed this needs to be disabled anyway as you say, I believe using the pytest interface is more appropriate. Another issue appeared this week with the same test, but it's not due to the same problem (see [this PR](https://github.com/root-project/root/pull/13926)) and is already fixed.

**Pull request merged**
