### PR TITLE
Add 'auto' keyword to variable declarations

### PR DESCRIPTION
**Pull request by devajithvs**
This is related to: https://github.com/root-project/root/pull/14645

The failing checks in the above PR are due to warnings added interfering with the test outputs.

### CODE REVIEW

**Comment by pcanal** [comment]
Can you double check that after this PR, all trace of `ClingWorkAroundMissingImplicitAuto` have been removed?

**Comment by devajithvs** [comment]
> Can you double check that after this PR, all trace of `ClingWorkAroundMissingImplicitAuto` have been removed?

The only instance remaining is here: https://github.com/root-project/roottest/blob/d3205d40565c414df8c7445b104de5b2871f4228/scripts/FixCling.mk#L128

`ifneq ($(ClingReinstateRedeclarationAllowed)-$(ClingWorkAroundMissingImplicitAuto),yes-)`

Other instances (in the same file) are commented out by one of the previous commits. Should I remove that too?

**Comment by devajithvs** [comment]
> Can you double check that after this PR, all trace of `ClingWorkAroundMissingImplicitAuto` have been removed?

Removed all instances of `ClingWorkAroundMissingImplicitAuto`

**Review by hahnjo — APPROVED** [review]
LGTM; we could also get rid of `ClingWorkAroundExtraParensWithImplicitAuto` at the same time.

FWIW this can be merged before / without the corresponding https://github.com/root-project/root/pull/14645 as I think it's an improvement overall, getting rid of non-standard C++.

**Comment by devajithvs** [comment]
Removed instances of `ClingWorkAroundExtraParensWithImplicitAuto` too

**Pull request merged**
