### PR TITLE
Test fixes for mac13(arm)

### PR DESCRIPTION
**Pull request by hahnjo**

### CODE REVIEW

**Comment by hahnjo** [comment]
@phsft-bot build!

**Comment by hahnjo** [comment]
Hm, apparently roottest PRs are not automatically rebased on `master` :cry: anyway, I verified that the changes fix the two tests on mac13(arm) - another step closer to green builds.

**Review by Axel-Naumann — COMMENTED** [review]
OK for `root/meta` (similar to 06b83ef19d7f5762863ab5f1ec6882ee0d2285ab); we need Jonas for `root/roofitstats/vectorisedPDFs/testLognormal.cxx`

**Comment by hahnjo** [comment]
@guitargeek could you take a quick look here? Thanks!

**Review by guitargeek — APPROVED** [review]
Thanks for the fix! It's fine to slightly change the tolerances here, they are arbitrary anyway.

**Pull request merged**
