### PR TITLE
Add tests for chunked TThreadExecutor::Foreach

### PR DESCRIPTION
**Pull request by xvallspl**

### CODE REVIEW

**Comment by xvallspl** [comment]
Related to https://github.com/root-project/root/pull/2632

**Comment by xvallspl** [comment]
@phsft-bot build!

**Comment by xvallspl** [comment]
@phsft-bot build!

**Comment by xvallspl** [comment]
@phsft-bot build

**Comment by xvallspl** [comment]
@bluehood @dpiparo @amadio I see this happening again and again but I can't see how my PR affects it.

**Comment by bluehood** [comment]
@xvallspl it doesn't, for some reason you are running on an old `roottest`.
do you have a `foreach` branch in your `roottest` fork that might be picked up instead of `master`?

**Pull request merged**
