### PR TITLE
[PyROOT] New unit test with reproducer from ROOT issue 14232

### PR DESCRIPTION
**Pull request by guitargeek**
See https://github.com/root-project/root/issues/14232.

### CODE REVIEW

**Comment by guitargeek** [comment]
We should probably merge this PR, since there is no failure in the CI, and like this we can maybe see the problem in the nightlies at some point (or just close the linked issue if the problem with the `tuple_element` turns out to not be reproducible at all).

**Comment by dpiparo** [comment]
I agree.

**Comment by guitargeek** [comment]
@dpiparo, can you please approve this PR so I can merge it? Thanks

**Review by dpiparo — APPROVED** [review]
LGTM! thanks for this nice test.

**Pull request merged**
